server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: loo-svc
  redis:
    host: ${REDIS_HOST:redis}
  port: ${REDIS_PORT:6379}

opentracing:
  jaeger:
    enable-b3-propagation: true
    udp-sender:
      host: ${JAEGER_UDP_SENDER_HOST:localhost}
  spring:
    web:
      enabled: ${OPENTRACING_SPRING_WEB_ENABLED:true}
